name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Playwright
        run: bun install && bunx playwright install chromium

      - name: Start server
        run: docker compose up -d

      - name: Run tests
        run: bun test

      - name: Stop server
        run: docker compose down

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t netmap .

      # Optional: push to registry
      # - name: Push to GitHub Container Registry
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #     docker tag netmap ghcr.io/${{ github.repository }}:latest
      #     docker push ghcr.io/${{ github.repository }}:latest
